/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'work-types': WorkType;
    media: Media;
    projects: Project;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'work-types': WorkTypesSelect<false> | WorkTypesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'calculator-settings': CalculatorSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'calculator-settings': CalculatorSettingsSelect<false> | CalculatorSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Виды работ для проектов, калькулятора и публичных страниц услуг.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-types".
 */
export interface WorkType {
  id: number;
  title: string;
  /**
   * Для карточки на /services. Без маркетинговых обещаний.
   */
  shortDescription?: string | null;
  /**
   * Полное описание на странице услуги.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Необязательно. Можно загрузить прямо здесь.
   */
  cover?: (number | null) | Media;
  showOnServicesPage?: boolean | null;
  featured?: boolean | null;
  /**
   * Выключенные виды не показываются публично.
   */
  active?: boolean | null;
  /**
   * Для новых записей генерируется из названия. Существующие slug не меняйте без необходимости.
   */
  slug: string;
  /**
   * Меньше — выше в списке.
   */
  sortOrder?: number | null;
  /**
   * Если пусто: «{Название} в Туле — MBN Строй».
   */
  seoTitle?: string | null;
  /**
   * Если пусто — из короткого описания или нейтральный текст.
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Техническая медиатека. Основной workflow — загрузка файлов прямо из формы Проекта (обложка и разделы).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Необязательно. Если пусто — на сайте подставится автоматически из названия раздела и проекта.
   */
  alt?: string | null;
  /**
   * Необязательно. Не нужна для обычной загрузки фото.
   */
  caption?: string | null;
  /**
   * Необязательно. Полезно для вертикальных видео и фото.
   */
  orientation?: ('landscape' | 'portrait' | 'square') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Создайте проект, укажите виды работ, добавьте разделы и загрузите фото/видео прямо в форму — затем Publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  location: string;
  /**
   * м²
   */
  area?: number | null;
  projectType: 'apartment' | 'house' | 'commercial' | 'room';
  renovationType?: ('cosmetic' | 'capital' | 'turnkey') | null;
  /**
   * Число
   */
  durationValue?: number | null;
  /**
   * День / месяц / год
   */
  durationUnit?: ('day' | 'month' | 'year') | null;
  year?: number | null;
  description?: string | null;
  /**
   * Перетащите или выберите файл. Alt и подпись заполнять не обязательно.
   */
  cover?: (number | null) | Media;
  /**
   * Например: отделка, электрика, сантехника, натяжные потолки.
   */
  workTypes?: (number | WorkType)[] | null;
  /**
   * Порядок разделов = порядок на странице проекта. Перетаскивайте для сортировки.
   */
  sections?:
    | {
        /**
         * Например: «Ванная» или «Натяжные потолки».
         */
        title: string;
        /**
         * Необязательно. Для разделов по виду работ (например натяжные потолки) оставьте пустым.
         */
        roomType?:
          | (
              | 'bathroom'
              | 'kitchen'
              | 'bedroom'
              | 'living-room'
              | 'balcony'
              | 'hallway'
              | 'floor'
              | 'interior'
              | 'other'
            )
          | null;
        /**
         * Какие работы показаны в этом разделе (связка медиа ↔ вид работ).
         */
        workTypes?: (number | WorkType)[] | null;
        description?: string | null;
        /**
         * Достаточно выбрать или перетащить файлы. Порядок сохраняется.
         */
        mediaItems?:
          | {
              media: number | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  /**
   * Генерируется из названия автоматически. Меняйте только при необходимости.
   */
  slug: string;
  /**
   * Необязательно. Если не задан — на сайте сортировка по дате публикации.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Заявки с сайта. Публичный доступ к списку закрыт.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  displayTitle?: string | null;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Необязательно. Заполняется, если пользователь указал.
   */
  preferredContact?: ('phone' | 'telegram' | 'whatsapp' | 'email') | null;
  comment?: string | null;
  /**
   * Устанавливается сайтом автоматически.
   */
  source: 'contact' | 'calculator' | 'project' | 'service' | 'other';
  contextType?: ('project' | 'service') | null;
  contextSlug?: string | null;
  hasCalculatorSnapshot?: boolean | null;
  /**
   * Снимок того, что видел пользователь. Не пересчитывается.
   */
  calculatorSummary?: string | null;
  calculatorSnapshot?: {
    objectType?: ('apartment' | 'house' | 'commercial') | null;
    apartmentLayout?: ('studio' | '1-room' | '2-room' | '3-room' | '4-plus') | null;
    area?: number | null;
    renovationType?: ('cosmetic' | 'capital' | 'turnkey') | null;
    condition?: ('new-build' | 'secondary' | 'rough') | null;
    workTypes?:
      | {
          slug: string;
          title?: string | null;
          id?: string | null;
        }[]
      | null;
    estimateMin?: number | null;
    estimateMax?: number | null;
    calculatedAt?: string | null;
  };
  status: 'new' | 'in-progress' | 'contacted' | 'completed' | 'spam';
  consentAccepted: boolean;
  consentAcceptedAt?: string | null;
  consentVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'work-types';
        value: number | WorkType;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-types_select".
 */
export interface WorkTypesSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  description?: T;
  cover?: T;
  showOnServicesPage?: T;
  featured?: T;
  active?: T;
  slug?: T;
  sortOrder?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  orientation?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  location?: T;
  area?: T;
  projectType?: T;
  renovationType?: T;
  durationValue?: T;
  durationUnit?: T;
  year?: T;
  description?: T;
  cover?: T;
  workTypes?: T;
  sections?:
    | T
    | {
        title?: T;
        roomType?: T;
        workTypes?: T;
        description?: T;
        mediaItems?:
          | T
          | {
              media?: T;
              id?: T;
            };
        id?: T;
      };
  featured?: T;
  slug?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  displayTitle?: T;
  name?: T;
  phone?: T;
  email?: T;
  preferredContact?: T;
  comment?: T;
  source?: T;
  contextType?: T;
  contextSlug?: T;
  hasCalculatorSnapshot?: T;
  calculatorSummary?: T;
  calculatorSnapshot?:
    | T
    | {
        objectType?: T;
        apartmentLayout?: T;
        area?: T;
        renovationType?: T;
        condition?: T;
        workTypes?:
          | T
          | {
              slug?: T;
              title?: T;
              id?: T;
            };
        estimateMin?: T;
        estimateMax?: T;
        calculatedAt?: T;
      };
  status?: T;
  consentAccepted?: T;
  consentAcceptedAt?: T;
  consentVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Контакты и базовые данные компании для шапки, подвала и страницы «Контакты».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName?: string | null;
  slogan?: string | null;
  location?: string | null;
  /**
   * Пустые поля на сайте не показываются. Не заполняйте заглушками.
   */
  contacts?: {
    /**
     * Например: +7 (4872) 00-00-00
     */
    phone?: string | null;
    email?: string | null;
    /**
     * URL (https://t.me/…) или username (@name / name).
     */
    telegram?: string | null;
    /**
     * URL (https://wa.me/…) или номер (+79001234567).
     */
    whatsapp?: string | null;
    /**
     * Например: Пн–Пт, 10:00–19:00
     */
    workingHours?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Цены и коэффициенты для калькулятора на сайте. Формула расчёта фиксирована в коде и здесь не редактируется.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculator-settings".
 */
export interface CalculatorSetting {
  id: number;
  enabled?: boolean | null;
  /**
   * ₽. Итоговый минимум не ниже этого значения.
   */
  minimumPrice: number;
  /**
   * ₽. Например 10000 → 1 480 000, а не 1 483 472.
   */
  roundingStep: number;
  /**
   * ₽ за м². Диапазон min–max для типа объекта и ремонта.
   */
  baseRates?:
    | {
        objectType: 'apartment' | 'house' | 'commercial';
        renovationType: 'cosmetic' | 'capital' | 'turnkey';
        active?: boolean | null;
        minPricePerM2: number;
        maxPricePerM2: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Множители к базовой стоимости.
   */
  conditionRules?:
    | {
        condition: 'new-build' | 'secondary' | 'rough';
        active?: boolean | null;
        minMultiplier: number;
        maxMultiplier: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Если «Входит в базу» — работа видна в wizard, но не добавляет цену отдельно.
   */
  workRules?:
    | {
        workType: number | WorkType;
        pricingMode: 'per_m2' | 'fixed' | 'percent';
        includedInBase?: boolean | null;
        active?: boolean | null;
        /**
         * ₽/м², ₽ или % — в зависимости от способа расчёта.
         */
        minPrice: number;
        maxPrice: number;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  slogan?: T;
  location?: T;
  contacts?:
    | T
    | {
        phone?: T;
        email?: T;
        telegram?: T;
        whatsapp?: T;
        workingHours?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculator-settings_select".
 */
export interface CalculatorSettingsSelect<T extends boolean = true> {
  enabled?: T;
  minimumPrice?: T;
  roundingStep?: T;
  baseRates?:
    | T
    | {
        objectType?: T;
        renovationType?: T;
        active?: T;
        minPricePerM2?: T;
        maxPricePerM2?: T;
        id?: T;
      };
  conditionRules?:
    | T
    | {
        condition?: T;
        active?: T;
        minMultiplier?: T;
        maxMultiplier?: T;
        id?: T;
      };
  workRules?:
    | T
    | {
        workType?: T;
        pricingMode?: T;
        includedInBase?: T;
        active?: T;
        minPrice?: T;
        maxPrice?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}